// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can create a web project in the Firebase console.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can create a macos project in the Firebase console.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can create a windows project in the Firebase console.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can create a linux project in the Firebase console.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1gDMXZrMEWGDLLujydoDz-FSEGmaNw38',
    appId: '1:174837813637:android:7b7c63172575084c8cb4ec',
    messagingSenderId: '174837813637',
    projectId: 'ai-text-digitisation',
    storageBucket: 'ai-text-digitisation.firebasestorage.app',
  );

  // You need to replace these placeholder values with your actual Firebase configuration

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM2xUoqwinsgSXXx6otKQ4b_qi6P-YDxg',
    appId: '1:174837813637:ios:9bb3c6d110735e478cb4ec',
    messagingSenderId: '174837813637',
    projectId: 'ai-text-digitisation',
    storageBucket: 'ai-text-digitisation.firebasestorage.app',
    iosBundleId: 'br.com.raffashe.readit',
  );

}